void zerargame(){

//VARIAVEL X E Y DE TODOS OS ENEMY
sprites=1;
enemys_x=LIMITECAMPO;
enemys_y=4;

//DIRECAO ESQ=1 E DIR=2 
direction=2;

//ESPACO ENTRE INIMIGOS
ESPACO=10;

//ENEMY
ENEMY1_DISPARA=0;
ENEMY1_VIEW=1;
ENEMY1_X=LIMITECAMPO+1;
ENEMY1_Y=0;
ENEMY1_TIRO=0;
ENEMY1_TIROX=LIMITECAMPO+1;
ENEMY1_TIROY=0;

ENEMY2_DISPARA=0;
ENEMY2_VIEW=1;
ENEMY2_X=LIMITECAMPO+1;
ENEMY2_Y=0;
ENEMY2_TIRO=0;
ENEMY2_TIROX=LIMITECAMPO+1;
ENEMY2_TIROY=0;

ENEMY3_DISPARA=0;
ENEMY3_VIEW=1;
ENEMY3_X=LIMITECAMPO+1;
ENEMY3_Y=0;
ENEMY3_TIRO=0;
ENEMY3_TIROX=LIMITECAMPO+1;
ENEMY3_TIROY=0;

ENEMY4_DISPARA=0;
ENEMY4_VIEW=1;
ENEMY4_X=LIMITECAMPO+1;
ENEMY4_Y=0;
ENEMY4_TIRO=0;
ENEMY4_TIROX=LIMITECAMPO+1;
ENEMY4_TIROY=0;

ENEMY5_DISPARA=0;
ENEMY5_VIEW=1;
ENEMY5_X=LIMITECAMPO+1;
ENEMY5_Y=0;
ENEMY5_TIRO=0;
ENEMY5_TIROX=LIMITECAMPO+1;
ENEMY5_TIROY=0;

ENEMY6_DISPARA=0;
ENEMY6_VIEW=1;
ENEMY6_X=LIMITECAMPO+1;
ENEMY6_Y=0;
ENEMY6_TIRO=0;
ENEMY6_TIROX=LIMITECAMPO+1;
ENEMY6_TIROY=0;

ENEMY7_DISPARA=0;
ENEMY7_VIEW=1;
ENEMY7_X=LIMITECAMPO+1;
ENEMY7_Y=0;
ENEMY7_TIRO=0;
ENEMY7_TIROX=LIMITECAMPO+1;
ENEMY7_TIROY=0;

ENEMY8_DISPARA=0;
ENEMY8_VIEW=1;
ENEMY8_X=LIMITECAMPO+1;
ENEMY8_Y=0;
ENEMY8_TIRO=0;
ENEMY8_TIROX=LIMITECAMPO+1;
ENEMY8_TIROY=0;

ENEMY9_DISPARA=0;
ENEMY9_VIEW=1;
ENEMY9_X=LIMITECAMPO+1;
ENEMY9_Y=0;
ENEMY9_TIRO=0;
ENEMY9_TIROX=LIMITECAMPO+1;
ENEMY9_TIROY=0;

ENEMY1_SCORE=10;
ENEMY2_SCORE=7;
ENEMY3_SCORE=3;

player_x=LIMITECAMPO;
player_y=25;
player_vida=3;

tiro_ativo=0;
tiro_x=1;
tiro_y=0;

level=1;				
score=0;				

}
